### ISSUE TITLE
crosslet example not working

### ISSUE THREAD

**Issue by lcolladotor** [ramnathv/rMaps#1]
Hello,

I'm not sure if I'm doing something wrong or missing any pre-reqs, but the CrossLet example is not working for me.

```
> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rMaps_0.1

loaded via a namespace (and not attached):
[1] grid_3.0.2         lattice_0.20-24    plyr_1.8           rCharts_0.4.2     
[5] RColorBrewer_1.0-5 rjson_0.2.13       RJSONIO_1.0-3      whisker_0.3-2     
[9] yaml_2.1.10       
```

Here's the screenshot from the Google Chrome console. 

![screen shot 2014-02-10 at 10 32 54 am](https://f.cloud.github.com/assets/2288213/2126993/bbb680aa-9268-11e3-8034-7973b0e66c49.png)

DataMaps and Leaflet examples are working well.

Cheers,
Leo

**Comment by geertdobbels** [comment]
Hi, 

I get exactly the same results as bhuston above.... labels appear but no map. 
I am on Linux fedora 21, 
R version 3.1.3
Rstudio 0.99.386  (updated recently, but in previous version I had the same problem)
As with the others, the datamap and leaflet examples work fine.

Geert

**Comment by JasonAizkalns** [comment]
I receive the same results as @bhuston @cantgetthatping and @geertdobbels - I am able to see the labels/controls, but no map.

Here's the output from the Chrome console:

![image](https://cloud.githubusercontent.com/assets/5184911/8161153/100e8e5c-1343-11e5-8ccd-d616373374f6.png)

The `403 status` messages continue and they appear to come back with `Wrong API Key`.
