### ISSUE TITLE
Issue with namespaceExports() on Windows 10 64 bit

### ISSUE THREAD

**Issue by sunitprasad** [ramnathv/rMaps#103]
While installing rCharts both in github method (normal mode and dev mode) and by using the zip file, I get the below error : 

`** preparing package for lazy loading
Error in namespaceExport(ns, exports) : 
  undefined exports: as.yaml, yaml.load_file, yaml.load
ERROR: lazy loading failed for package 'rCharts`

The installation is successful on a Windows 8 platform. Any issues with the drive permissions, as my lib is in the C:\\ drive?

**Comment by ramnathv** [comment]
Can you try two things?

1. Reinstall the `yaml` package.
2. Restart your R session before loadng `rCharts`.

**Comment by sunitprasad** [comment]
Problem solved!! I reinstalled `yaml` and everything is working smooth.. Thank you, Mr Ramnath garu..
