### ISSUE TITLE
Plotting route using rMaps and leaflet routing machine plugin

### ISSUE THREAD

**Issue by natalyoussef** [ramnathv/rMaps#45]
Hi all!

I am new to using rMaps and leaflet. I would like to plot the route between two locations. The leaflet routing machine plugin allows us to do this (https://github.com/perliedman/leaflet-routing-machine). I am not quite sure how to use the functions addAssets() and setTemplate() to be able to use this plugin.

I have downloaded the "leaflet-routing-machine.min.js" file and saved in the same directory as my R code. I started playing a bit with the example that was given for rMaps. Here is my code so far:

![question](https://cloud.githubusercontent.com/assets/7190481/2623425/9fcf0164-bced-11e3-8b4a-211bbf75421d.png)

I appreciate any help!! Thank you!

**Comment by manoj8385** [comment]
Hi Ramnathv...Hope you fix map to work in Shiny

**Comment by tospig** [comment]
I posted [this answer on StackOverflow](http://stackoverflow.com/a/33358080/4002530) that uses the routing with shiny. Does this answer some of the questions here?

**Comment by JiyingWen** [comment]
Hi Ramnath, I have the same problem that when wrap the code into shiny, the map is there but the route is not showing. Could you help with that? Thanks! @ramnathv

**Comment by JiyingWen** [comment]
Hi @tospig I followed your way but the style is a bit off as you said..Is there a way to not show the text? or move the text to the side of the map? Thanks!

**Comment by JiyingWen** [comment]
@tospig Hi your method doesn't work as well....it worked yesterday....Thanks for any help!

**Comment by jingwen-z** [comment]
Hi @ramnathv , thanks a lot for such detailed writeup on your gist, it's really helpful! However, I met a problem but didn't find the solution, could you bring me some idea?
My computer is in WIN 7 system 64 bits, R is in version 3.4.0, R Studio is in version 1.0.143.
I installed the package `rMaps` as you said in your [github](https://github.com/ramnathv/rMaps), used exactly the same codes as yours in your [writeup](https://gist.github.com/ramnathv/9998388), but didn't get the route between two positions. Do I need to do something else before run the script?
