### ISSUE TITLE
rCharts Availability for R 3.1.0?

### ISSUE THREAD

**Issue by jatkat45** [ramnathv/rMaps#54]
I had an error stating that rCharts was not available for R version 3.1.0. Any idea of when this will be available?

**Comment by dhoreys** [comment]
Hi Ramnath:
I installed downloader package and then.
library(downloader)
download("https://github.com/ramnathv/rCharts/archive/master.tar.gz", "rCharts.tar.gz")

install.packages("rCharts.tar.gz", repos = NULL, type = "source")

Here I get an issue ...
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Warning in install.packages :
  running command '"C:/Program Files/R/R-3.1.1/bin/x64/R" CMD INSTALL -l "C:\EDA\myRLib" "rCharts.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘rCharts.tar.gz’ had non-zero exit status

**Comment by dhoreys** [comment]
I solved by issue.
I uninstalled prior version of R (3.1.1) and reinstalled R 3.1.2.
Updated r-studio (by going to rstudio's help and clicking for check for updates).
Then installed devtools.
and then installed devtools::install_github('ramnathv/rCharts')

This worked.
I think problem seemed to be with R version.
Thanks.

**Comment by thecapacity** [comment]
install.packages("base64enc") worked for me too, though I got some warnings when installing: install_github('ramnathv/rCharts@dev')

Warning in .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "Datamaps" of class "refClass"; definition not updated
Warning in .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "Datamaps" of class "refObject"; definition not updated
Warning in .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "Datamaps" of class "refClass"; definition not updated
Warning in .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "Leaflet" of class "refClass"; definition not updated
Warning in .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "Datamaps" of class "refObject"; definition not updated
Warning in .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "Leaflet" of class "refObject"; definition not updated

**Comment by thecapacity** [comment]
Also had to separately (and explicitly); install.packages("rjson")

**Comment by DavidAh** [comment]
Same issue as @catblue  - Example 1 doesn't display a map.   I have R 3.1.1 with R studio 0.98.1103 installed.  

>library(rMaps)
>crosslet( x="country", y=c("web_index", "universal_access", "impact_empowerment", "freedom_openness"), data = web_index)

**Comment by maheshwaria** [comment]
Same issue as posts above by DatidAh, thecapacity and others here is my code and I don't see any display and there are no errors, I have R3.1.1, Rstudio 0.98.1091 and rCharts successfully installed

nPlot(Freq~Hair,group='Eye',type='multiBarchart', data=subset(haireye,Sex='Male'))

**Comment by Jolly12** [comment]
How to install rstudio in window.

**Comment by Jolly12** [comment]
I am facing some problem while installing rstudio in my window.
