### ISSUE TITLE
Choropleth maps using custom layer

### ISSUE THREAD

**Issue by tyokota** [ramnathv/rMaps#6]
I recently came across http://rmaps.github.io/blog/posts/animated-choropleths/. Is it possible for rMaps to load a custom shape file for the base layer? Thanks!

**Comment by endri81** [comment]
I am having a lot of troubles.
Tried already http://geojson.io/ to create topojson and many other websites.
My shp files was with projection d3.geo.transverseMercator and still nothing shown :(

library(rMaps)
d1 <- Datamaps$new()
d1$set(
  geographyConfig = list(
    dataUrl = "https://www.dropbox.com/s/axn2qdic63hqvbu/map.topojson?dl=0"  
  ),
  scope = 'alb',
  setProjection = '#! function( element, options ) {
  
  var projection, path;
  
  projection = d3.geo.mercator()
  .center([-89, 21])

**Comment by ridhimagupta1191** [comment]
Hi,

I have been trying to create a custom map for India but the code runs well without displaying any map at the end. Can you please help me out with it ?

options(rcharts.cdn = TRUE)
d1 <- Datamaps$new()
d1

d1$set(
  geographyConfig = list(
    dataUrl = "IND_adm1.json",
    popupTemplate =  "#! function(geography, data) { //this function should just return a string
    return '<div class=hoverinfo><strong>' + geography.properties.NAME_1 + '</strong></div>';
    }  !#"
  ),
  dom = 'chart_1',
  scope = 'NAME_1',
  labels = TRUE,
  bodyattrs = "ng-app ng-controller='rChartsCtrl'",
  setProjection = '#! function( element, options ) {
  
  var projection, path;
  
  projection = d3.geo.mercator()
  .center([-89, 21])
  .scale(element.offsetWidth)
  .translate([element.offsetWidth / 2, element.offsetHeight / 2]);
  
  path = d3.geo.path()
  .projection( projection );
  
  return {path: path, projection: projection};
  } !#',
  fills = fills,
  data = dat2[[1]],
  legend = TRUE,
  labels = TRUE
)
d1

**Comment by ekstroem** [comment]
Try to make the necessary files available and I'll give it a look

**Comment by ridhimagupta1191** [comment]
https://drive.google.com/folderview?id=0B0dws70OAX9uM1k4aHJXM0lOalU&usp=sharing

**Comment by ekstroem** [comment]
Well I can confirm that I get a blank page just like you when I run your files. Are you sure the JSON file is in the correct format? How did you produce it? Maybe open another issue specific to your problem?

**Comment by dgohil** [comment]
The problem is with the shapefiles. The CRS of the shape file needs to be in WGS84 (any other projection will give you errors - so make sure your original shapefiles are in the right CRS. Smooth sailing after that).

This can easily be changed in QGIS, under the properties attributes.
