### ISSUE TITLE
Error: rCharts is not available (for R version 3.2.0)

### ISSUE THREAD

**Issue by roncampbell** [ramnathv/rMaps#97]
I tried installing on version 3.14 (I think) on Mac OS 10.10, then upgraded to R 3.2.0 after the initial error. Truncated error message:
* installing *source* package ‘rCharts’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(name) : there is no package called ‘base64enc’
Error : unable to load R code in package ‘rCharts’
ERROR: lazy loading failed for package ‘rCharts’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rCharts’
Error: Command failed (1)
> install_github('ramnathv/rMaps')
Downloading github repo ramnathv/rMaps@master
Installing rMaps
Installing dependencies for rMaps:
rCharts
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/hv/nvl_89pn0tx3d2vc0rvmx7j40000gn/T/RtmpRZen9M/devtools10bdf74892669/ramnathv-rMaps-dec6db2'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

ERROR: dependency ‘rCharts’ is not available for package ‘rMaps’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rMaps’
Error: Command failed (1)
In addition: Warning message:
package ‘rCharts’ is not available (for R version 3.2.0)

**Comment by ramnathv** [comment]
Install the `base64enc` package first and then install `rCharts` an `rMaps`. That should take care of the installation issues.

**Comment by roncampbell** [comment]
That did it. Thanks.
